version: "3"

services:

    database:
        image: mysql
        container_name: mysqldb
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: bancopichincha
        ports:
            - 3306:3306
        volumes:
            - ./bancoPichincha.sql:/docker-entrypoint-initdb.d/schema.sql:ro
        networks:
            - backendNetwork


    backend: 
        image: adoptopenjdk/openjdk8
        container_name: spring-backend-app
        ports:
            - 8080:8080
        volumes:
            - ./backend/target/test-0.0.1-SNAPSHOT.jar:/application.jar
        command: ["java", "-jar", "application.jar"]
        environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/bancopichincha
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
        depends_on:
            - database
        networks:
            - backendNetwork
            - frontendNetwork
           
    frontend:
        image: nginx:alpine
        container_name: angular
        ports: 
          - 4200:80
        depends_on:
          - backend
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ./frontend/dist/bancoPichinchaFrontend/:/usr/share/nginx/html
        networks:
          - frontendNetwork
    
networks:
    backendNetwork:
    frontendNetwork:
        